# Generated by Django 5.2.6 on 2025-09-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qnt_volume',
            field=models.IntegerField(default=0),
        ),
    ]
