# Generated by Django 5.2.6 on 2025-09-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_qnt_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
