# Generated by Django 5.2.6 on 2025-09-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_preco_custo_alter_produto_preco_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_maximo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
